---
version: "3.4"

kind: pipeline
type: docker
name: Checking for errors in YAML and python source code

services:
  - name: batfish
    image: batfish/batfish
    ports:
      - 9996: 9996
      - 9997: 9997

trigger:
  repo:
    - krimpas/small_topo
  branch:
    - dev_L3ifaces

steps:
  - name: Container info
    image: gkrimpas/small_topo:latest
    commands:
      - uname -v
      - ls -la 
      - env | grep BAT
  
  - name: Validating YAML RAW DATA files
    image: gkrimpas/small_topo:latest
    commands:
      - make black
      - make lint

  - name: Validating L3 interfaces YAML files
    image: gkrimpas/small_topo:latest
    commands:
      - make config

  - name: Validating batfish
    image: gkrimpas/small_topo:latest
    commands:
      - python3 $BATFISH_DIR/L3check.py
  
  - name: Validating num_of_ifaces
    image: gkrimpas/small_topo:latest
    commands:
      - python3 $BATFISH_DIR/L3check2.py

