---
version: "3.4"

kind: pipeline
type: docker
name: Checking for errors in YAML and python source code

trigger:
  repo:
    - krimpas/small_topo
  branch:
    - dev_L3ifaces

steps:

  - name: Greeting message
    image: alpine
    commands:
      - echo "Hello, this is a Drone CI pipeline!"
  
  - name: Container info
    image: gkrimpas/small_topo:latest
    commands:
      - uname -v
      - pwd
      - date
      - ls -la 
      - env | grep DIR
      - env | grep BAT
      - env

  - name: Validating YAML RAW DATA files
    image: gkrimpas/small_topo:latest
    commands:
      - echo "YAML RAW data/CHECKING fot YAML error and warnings"
      - yamllint --list-files --format github --strict $YML_DIR/r*/

  - name: Validating YAML SCHEMA files
    image: gkrimpas/small_topo:latest
    commands:
      - echo "YAML SCHEMA data/CHECKING fot YAML error and warnings"
      - yamllint --list-files --format github --strict $SCHEMA_DIR
  
  - name: Cerburus Python code Black
    image: gkrimpas/small_topo:latest
    commands:
      - echo "Cerburus Python code Black for formmating and warnings"
      - black $CERBERUS_DIR --check
      - black $BATFISH_DIR --check

  - name: Validating L3 interfaces YAML files
    image: gkrimpas/small_topo:latest
    commands:
      - python3 $CERBERUS_DIR/checkconfig.py --section interfaces
      - echo "End of L3 interfaces validation"

  - name: Validating OSPF settings YAML files
    image: gkrimpas/small_topo:latest
    commands:
      - python3 $CERBERUS_DIR/checkconfig.py --section ospf
      - echo "End of OSPF settings validation"

  - name: Validating OSPF keychains YAML files
    image: gkrimpas/small_topo:latest
    commands:
      - python3 $CERBERUS_DIR/checkconfig.py --section keychains
      - echo "End of OSPF keychains validation"

  - name: Validating batfish
    image: gkrimpas/small_topo:latest
    commands:
      - python3 $BATFISH_DIR/L3check.py

