---
version: "3.4"

kind: pipeline
type: docker
name: NetDevOps CI/CD Pipeline

services:
  - name: batfish
    image: batfish/batfish
    ports:
      - 9996: 9996
      - 9997: 9997

trigger:
  repo:
    - krimpas/small_topo
  branch:
    - dev_L3ifaces

steps:
  - name: Container info
    image: gkrimpas/small_topo:latest
    commands:
      - uname -v
      - ls -la 
      - env | grep BAT
  
#  - name: Black & YamlLint YAML DATA & SCHEMA files
#    image: gkrimpas/small_topo:latest
#    commands:
#      - make black
#      - make lint

#  - name: Cerberizing L3 / OSPF YAML files
#    image: gkrimpas/small_topo:latest
#    commands:
#      - make config

  - name: Batfishing L3 / OSPF YAML files
    image: gkrimpas/small_topo:latest
    commands:
      - make black
      - make lint
      - make config
      - make batfish