---
version: "3.4"

kind: pipeline
type: docker
name: Checking for errors in YAML and pythob source code

trigger:
  repo:
    - krimpas/small_topo
  branch:
    - dev_L3ifaces
    - main

steps:

  - name: Greeting messaghe
    image: alpine
    commands:
      - echo "Hello, this is a Drone CI pipeline!"
  
  - name: Container info
    image: gkrimpas/net_topo:latest
    commands:
      - uname -v
      - pwd
      - date
      - ls -la code
      - env | grep DIR

  - name: Validating YAML RAW DATA files
    image: gkrimpas/net_topo:latest
    commands:
      - echo "YAML RAW data/CHECKING fot YAML error and warnings"
      - yamllint --list-files --format github --strict $YML_DIR/r*/

  - name: Validating YAML SCHEMA files
    image: gkrimpas/net_topo:latest
    commands:
      - echo "YAML SCHEMA data/CHECKING fot YAML error and warnings"
      - yamllint --list-files --format github --strict $SCHEMA_DIR
  
  - name: Black formatter on Python source code
    image: gkrimpas/net_topo:latest
    commands:
      - echo "Black on Python source code"
      - black $CODE_DIR/ --check

  - name: Validating L3 interfaces YAML files
    image: gkrimpas/net_topo:latest
    commands:
      - python code/checkconfig.py --section interfaces
      - echo "End of L3 interfaces validation"

  - name: Validating OSPF settings YAML files
    image: gkrimpas/net_topo:latest
    commands:
      - python code/checkconfig.py --section ospf
      - echo "End of OSPF settings validation"

  - name: Validating OSPF keychains YAML files
    image: gkrimpas/net_topo:latest
    commands:
      - python code/checkconfig.py --section keychains
      - echo "End of OSPF keychains validation"
    
