---
inventory:
    plugin: SimpleInventory
    options:
         host_file: "inv/hosts.yaml"
         group_file: "inv/groups.yaml"
         defaults_file: "inv/defaults.yaml"
runner:
    plugin: threaded
    options:
         num_workers: 16

