---
r1:
    hostname: 192.168.1.12
    port: 22
    username: cisco
    password: cisco
    platform: ios
    groups:
         - routers
    data:
        site: nafplio
        role: router
        type: router
        conf_sections:
            - interfaces
            - ospf

r2:
    hostname: 192.168.1.10
    port: 22  
    username: cisco  
    password: cisco
    platform: ios  
    groups:
         - routers
    data:
        site: kalamata
        role: router
        type: router
        conf_sections:
            - interfaces
            - ospf
r3:
    hostname: 192.168.1.11
    username: cisco  
    password: cisco
    platform: ios  
    groups:
         - routers
    data:
        site: athens
        role: router
        type: router
        conf_sections:
            - interfaces
            - ospf
            - keychains

r4:
    hostname: 192.168.1.9
    port: 22  
    username: cisco  
    password: cisco
    platform: ios  
    groups:
         - routers
    data:
        site: kalamata
        role: router
        type: router
        conf_sections:
            - interfaces
            - ospf
r5:
    hostname: 192.168.1.8
    port: 22  
    username: cisco  
    password: cisco
    platform: ios  
    groups:
         - routers
    data:
        site: patra
        role: router
        type: router
        conf_sections:
            - interfaces
            - ospf
            - keychains
